### ISSUE TITLE
Kured shedule reboot issue

### ISSUE THREAD

**Issue by Boriszn** [weaveworks/kured#179]
Hey Kured team

We've installed Kured to our AKS cluster (version 1.17.1), using Helm chart. 
Kured [Helm Release 2.1.1](https://hub.helm.sh/charts/kured/kured/2.1.1) (Kured app version 1.4.5)

*Problem*
In configuration, I set start time `startTime: "0:00"` and `endTime: "04:00"` 
Sometime update and reboot are trigered after 4 pm which is wrong. Image below

![image](https://user-images.githubusercontent.com/12999498/91049942-43419400-e61e-11ea-9ad9-f60c859b6107.png)

Could you please suggest what I'm doing wrong? Perhaps I have forgotten some config option?
Thanks in advance.

We used following helm (values.yaml) configuration
```
image:
  repository: weaveworks/kured
  tag: 1.4.5
  pullPolicy: IfNotPresent
  pullSecrets: []

updateStrategy: OnDelete

podAnnotations: {}

extraArgs: {}

extraEnvVars:
#  - name: slackHookUrl
#    valueFrom:
#      secretKeyRef:
#        name: secret_name
#        key: secret_key
#  - name: regularEnvVariable
#    value: 123

configuration:
  annotationTtl: 0          # force clean annotation after this ammount of time (default 0, disabled)
  alertFilterRegexp: ""     # alert names to ignore when checking for active alerts
  blockingPodSelector: []   # label selector identifying pods whose presence should prevent reboots
  endTime: "04:00"               # only reboot before this time of day (default "23:59")
  lockAnnotation: ""        # annotation in which to record locking node (default "weave.works/kured-node-lock")
  period: ""                # reboot check period (default 1h0m0s)
  prometheusUrl: ""         # Prometheus instance to probe for active alerts
  rebootDays: [mo,tu,we,th,fr]            # only reboot on these days (default [su,mo,tu,we,th,fr,sa])
  rebootSentinel: ""        # path to file whose existence signals need to reboot (default "/var/run/reboot-required")
  slackChannel: ""          # slack channel for reboot notfications
  slackHookUrl: ""          # slack hook URL for reboot notfications
  slackUsername: ""         # slack username for reboot notfications (default "kured")
  startTime: "0:00"         # only reboot after this time of day (default "0:00")
  timeZone: "UTC"           # time-zone to use (valid zones from "time" golang package)

rbac:
  create: true

serviceAccount:
  create: true
  name:

podSecurityPolicy:
  create: false

resources: {}

metrics:
  create: false
  namespace: ""
  labels: {}
  interval: 60s
  scrapeTimeout: ""

service:
  create: false
  port: 8080
  annotations: {}

priorityClassName: ""

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

affinity: {}

nodeSelector: {}
```
