### ISSUE TITLE
Unknown flag error for reboot-days on 1.5.1

### ISSUE THREAD

**Issue by jack-education** [weaveworks/kured#286]
After deploying the daemon with the same manifest as https://github.com/weaveworks/kured/releases/download/1.5.1/kured-1.5.1-dockerhub.yaml

except with the command flag added:

`--reboot-days mon,tue,wed,thu,fri`

so the containers config is:

```
containers:
  - name: kured
    image: docker.io/weaveworks/kured:1.5.1
            # If you find yourself here wondering why there is no
            # :latest tag on Docker Hub,see the FAQ in the README
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true # Give permission to nsenter /proc/1/ns/mnt
    env:
      # Pass in the name of the node on which this pod is scheduled
      # for use with drain/uncordon operations and lock acquisition
      - name: KURED_NODE_ID
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    command:
      - /usr/bin/kured
      - --reboot-days mon,tue,wed,thu,fri
```

The pods go into a CrashBackLoopOff/Error state with the log on a pod of:

> Error: unknown flag: --reboot-days mon,tue,wed,thu,fri

The added flag matches the commented out flag in https://github.com/weaveworks/kured/releases/download/1.5.1/kured-1.5.1-dockerhub.yaml and https://github.com/weaveworks/kured#setting-a-schedule

Is something missing in my configuration?

Thanks
