### ISSUE TITLE
Deprecated flag(s). Please use --notify-url flag instead.

### ISSUE THREAD

**Issue by Tetradeus** [weaveworks/kured#409]
When using last helm version (2.7.1) and setting value in 'configuration.notifyUrl', we get a deprecation message in kured pods :

```
time="2021-07-20T08:55:06Z" level=warning msg="Deprecated flag(s). Please use --notify-url flag instead."
```

**Comment by anderius** [comment]
I am experiencing the same with Helm chart version 2.9.0.

**Comment by ckotzbauer** [comment]
@Tetradeus Do you use the `--slack-channel`, `--slack-hook-url` or `--slack-username` flag (in addition to the `--notify-url`?
Then this message is emitted, as the slack-flags are deprecated and should not be used together with the new `--notify-url` parameter from shoutrrr.

**Comment by jgilfoil** [comment]
I'm getting this issue on chart version 2.9.1

```
    configuration:
      timeZone: "America/New_York"
      startTime: "4:00"
      endTime: "10:00"
      notifyUrl: "${SECRET_KURED_DISCORD_WEBHOOK}"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
```
`time="2021-09-30T00:55:10Z" level=warning msg="Deprecated flag(s). Please use --notify-url flag instead."`

**Comment by ckotzbauer** [comment]
This misleading warning was fixed with #382 and will be released in a few days with the upcoming release (1.8.0).
The `--slack-username` parameter has a default-value, so the warning appeared even if you don't set a `--slack*` parameter by yourself.

**Comment by Tetradeus** [comment]
Hello @ckotzbauer ,

Sorry for my late reply. I do not use slack nor any slack specific parameters. 
I only use notify url via the helm chart setting value 'configuration.notifyUrl',

Thanks.

**Comment by Tetradeus** [comment]
Here is the limited computed values I see in my helm chart release : 

```
configuration:
  alertFilterRegexp: ""
  annotateNodes: false
  blockingPodSelector: []
  endTime: "04:00"
  lockAnnotation: ""
  lockReleaseDelay: 0
  lockTtl: 0
  messageTemplateDrain: ""
  messageTemplateReboot: ""
  notifyUrl: teams://xxxxx
  period: 1h0m0s
  prometheusUrl: ""
  rebootCommand: /bin/systemctl reboot
  rebootDays:
  - sun
  rebootSentinel: ""
  slackChannel: ""
  slackHookUrl: ""
  slackUsername: ""
```

Is the slackUsername default value "" ? Is this causing the warning ? Thanks.
