### ISSUE TITLE
Add ability to modify containerSecurityContext in Helm Chart

### ISSUE THREAD

**Issue by losil** [weaveworks/kured#521]
## Problem

We are running our kubernetes clusters with one single privileged podsecuritypolicy which is allowing everything:

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: system-unrestricted-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```

Kured is deployed with the Helm chart and without creating the specific Kured-PSP (`podSecurityPolicy.create: false`). That means the Kured pods are using the `system-unrestricted-psp` psp. This leads to the following error `cannot set allowPrivilegeEscalation to false and privileged to true`:

```
Warning  FailedCreate      12m                  daemonset-controller  Error creating: Pod "kured-dev-6mk7j" is invalid: spec.containers[0].securityContext: Invalid value: core.SecurityContext{Capabilities:(*core.Capabilities)(nil), Privileg ¦
¦ ed:(*bool)(0xc047b39ed7), SELinuxOptions:(*core.SELinuxOptions)(nil), WindowsOptions:(*core.WindowsSecurityContextOptions)(nil), RunAsUser:(*int64)(nil), RunAsGroup:(*int64)(nil), RunAsNonRoot:(*bool)(nil), ReadOnlyRootFilesystem:(*bool)(nil) ¦
¦ , AllowPrivilegeEscalation:(*bool)(0xc04c64f100), ProcMount:(*core.ProcMountType)(nil), SeccompProfile:(*core.SeccompProfile)(nil)}: cannot set `allowPrivilegeEscalation` to false and `privileged` to true
```

Because the container securityContext of the Kured daemonset only considers the parameter `privileged: true` and not also `allowPrivilegeEscalation: true` the pods cannot be created. The option from the global psp `defaultAllowPrivilegeEscalation: false` disables the privilege escalation which leads to the error above. Editing the created daemonset and adding the option `allowPrivilegeEscalation: true` to the container securityContext helps and the pods work successfully.

## Solution

It would solve our issue if the container securityContext can be managed via the Helm Chart values. Currently the securityContext is hardcoded in [templates/daemonset.yaml](https://github.com/weaveworks/kured/blob/main/charts/kured/templates/daemonset.yaml#L53):

```yaml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true # Give permission to nsenter /proc/1/ns/mnt
          resources:
```

A value section like the following would suffice:

```yaml
containerSecurityContext:
  privileged: true
  allowPrivilegeEscalation: true #optional when psp of kured chart will be deployed
```
