### ISSUE TITLE
Cron jobs

### ISSUE THREAD

**Issue by vitobotta** [weaveworks/kured#72]
Hi! Thanks for kured, very useful. I was wondering, if I have scheduled backups and right during a backup kured detects that a node requires rebooting, will the backups or any other cron jobs complete first or will they be terminated or something? Thanks

**Comment by awh** [comment]
Hi @vitobotta - interesting question. Are these cron jobs configured at the OS level or are they kubernetes CronJob resources? If they're the latter, you can use the new [blocking reboots via pods](https://github.com/weaveworks/kured#blocking-reboots-via-pods) feature in kured 1.2.0. If it's the former, I'm not sure what will happen to be honest - kured just runs `systemctl reboot`, so unless that happens to interact gracefully with running cron jobs and lets them run to completion, they'll probably just get terminated.

**Comment by vitobotta** [comment]
Hi @awh , I was referring to Kubernetes cron jobs since I prefer not doing anything outside K8S if I am using K8S for my apps. I checked that page but there would be a problem with the name of the pods used by cron jobs because they change. For example when MySQL jobs are running the jobs are named something like `mysql-cluster-auto<timestamp>-backup`. Any ideas of how to handle this? Thanks!

**Comment by awh** [comment]
@vitobotta great, that makes things much simpler. You can specify additional labels on the pods created by `CronJob` resources - you have to get them in the right place though:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: backup-cronjob
spec: # CronJobSpec
    jobTemplate: #JobTemplateSpec
        spec: #JobSpec
            template: # PodTemplateSpec
                metadata:
                    labels:
                        block-reboots: true
                spec:
                        ...
```

then add

```
--blocking-pod-selector=block-reboots=true
```

to your kured configuration.
