### ISSUE TITLE
Error acquiring lock: daemonsets.apps \"kured\" is forbidden: User \"system:serviceaccount:kube-system:kured\" cannot update resource \"daemonsets\" in API group \"apps\" in the namespace \"kube-system\""

### ISSUE THREAD

**Issue by nicolas-marcq** [weaveworks/kured#99]
On the last version from master (4beddb5338)
Here si my logs
```
 time="2019-11-21T10:55:37Z" level=info msg="Kubernetes Reboot Daemon: master-4beddb5"
time="2019-11-21T10:55:37Z" level=info msg="Node ID: aks-nodepool1-25168911-0"
time="2019-11-21T10:55:37Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2019-11-21T10:55:37Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1m0s"
time="2019-11-21T10:55:37Z" level=info msg="Blocking Pod Selectors: []"
time="2019-11-21T10:55:37Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 00:00 and 23:59 UTC"
time="2019-11-21T10:56:18Z" level=info msg="Reboot required"
time="2019-11-21T10:56:18Z" level=fatal msg="Error acquiring lock: daemonsets.apps \"kured\" is forbidden: User \"system:serviceaccount:kube-system:kured\" cannot update resource \"daemonsets\" in API group \"apps\" in the namespace \"kube-system\"" 
```

My rbac config:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: kured
      rules:
      # Allow kured to read spec.unschedulable
      # Allow kubectl to drain/uncordon
        - apiGroups: [""]
          resources: ["nodes"]
          verbs:     ["get", "patch"]
        - apiGroups: [""]
          resources: ["pods"]
          verbs:     ["list","delete","get"]
        - apiGroups: ["extensions"]
          resources: ["daemonsets"]
          verbs:     ["get"]
        - apiGroups: [""]
          resources: ["pods/eviction"]
          verbs:     ["create"]
        - apiGroups: ["apps"]
          resources: ["daemonsets"]
          verbs:     ["get", "list", "patch", "delete", "put"]
```
